### ISSUE TITLE
ERROR with command in makefile

### ISSUE THREAD

**Issue by Sa1Vation** [patrikarlos/np_assignment1#1]
The error happend when I make this project "ar: -o: No such file or directory",
I think the cause of errror is in Makefile line 32. I don't know which file you want to backup.
Looking forward to your reply ^_^

**Comment by patrikarlos** [comment]
Your system misses the 'ar' command. Verify that you have installed build-essential for Ubuntu-based systems, for other distributions find the corresponding package.

**Comment by Sa1Vation** [comment]
Emm...I use MacOS instead of ubuntu, and I'm sure that my system has installed the 'ar' command. Because when I execute
`ar`
the response is 
 ✘ salvation@Yuehans-MacBook-Pro  ~  ar
usage:  ar -d [-TLsv] archive file ...
        ar -m [-TLsv] archive file ...
        ar -m [-abiTLsv] position archive file ...
        ar -p [-TLsv] archive [file ...]
        ar -q [-cTLsv] archive file ...
        ar -r [-cuTLsv] archive file ...
        ar -r [-abciuTLsv] position archive file ...
        ar -t [-TLsv] archive [file ...]
        ar -x [-ouTLsv] archive [file ...]

It looks that my ar tool doesn't have '-o' option. I think the cause maybe the version of ar...

**Comment by Sa1Vation** [comment]
I don't what is the usage of '-o' option, so I google it. I find out the usage of '-o' option in [https://www.ibm.com/docs/en/aix/7.1?topic=ar-command](url).
It said that '-o' option is to 'Orders the members of the archive to ensure maximum loader efficiency with a minimum amount of unused space. In almost all cases, the -o flag physically positions the archive members in the order in which they are logically linked. The resulting archive is always written in the big archive format, so this flag can be used to convert a small-format archive to a big-format archive.'.
So I try to delete '-o' option of 'ar' command in Makefile. Now I can 'make' this project successfully.
Is it correct to delete '-o' option?

**Comment by patrikarlos** [comment]
Ok, if it worked then we try.

I'll try to change the Makefile as to dynamically build using either the std.syntax (i.e. the current), or if it detects it's running on a mac, the mac syntax.

I'll just verify what -o means on my system. Usually -o means output, i.e. -o <file>, would save to 'file'.

Thank you for the input.

Br Patrik

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________
